export const mentors = [
  {
    name: "Felix",
    password: "test",
    email: "test@email.com",
    username: "r123456",
    rol: "Mentor",
  },
  {
    name: "Frans",
    password: "test",
    email: "test@email.com",
    username: "r123456",
    rol: "Mentor",
  },
  {
    name: "Fons",
    password: "test",
    email: "test@email.com",
    username: "r123438",
    rol: "Mentor",
  },
  {
    name: "Frank",
    password: "test",
    email: "test@email.com",
    username: "r123458",
    rol: "Mentor",
  },
  {
    name: "Alice",
    password: "alice123",
    email: "alice@email.com",
    username: "alice123",
    rol: "Mentor",
  },
  {
    name: "Bob",
    password: "bob456",
    email: "bob@email.com",
    username: "bob456",
    rol: "Mentor",
  },
  {
    name: "Charlie",
    password: "charlie789",
    email: "charlie@email.com",
    username: "charlie789",
    rol: "Mentor",
  },
  {
    name: "David",
    password: "david111",
    email: "david@email.com",
    username: "david111",
    rol: "Mentor",
  },
  {
    name: "Grace",
    password: "grace2023",
    email: "grace@email.com",
    username: "grace23",
    rol: "Mentor",
  },
  {
    name: "Henry",
    password: "henry456",
    email: "henry@email.com",
    username: "henry789",
    rol: "Mentor",
  },
  {
    name: "Isabella",
    password: "isabella123",
    email: "isabella@email.com",
    username: "isabella12",
    rol: "Mentor",
  },
  {
    name: "Jack",
    password: "jack567",
    email: "jack@email.com",
    username: "jack456",
    rol: "Mentor",
  },
  {
    name: "Karen",
    password: "karen999",
    email: "karen@email.com",
    username: "karen333",
    rol: "Mentor",
  },
  {
    name: "Liam",
    password: "liam789",
    email: "liam@email.com",
    username: "liam456",
    rol: "Mentor",
  },
  {
    name: "Mia",
    password: "mia111",
    email: "mia@email.com",
    username: "mia789",
    rol: "Mentor",
  },
];
