export const students = [
  {
    username: "r12345",
    name: "Felix",
    email: "felix@example.com",
    password: "password123",
    role: "Student",
  },
  {
    username: "r67890",
    name: "Sophia",
    email: "sophia@example.com",
    password: "securepass",
    role: "Student",
  },
  {
    username: "r54321",
    name: "Oliver",
    email: "oliver@example.com",
    password: "mypassword",
    role: "Student",
  },
  {
    username: "r98765",
    name: "Emma",
    email: "emma@example.com",
    password: "12345pass",
    role: "Student",
  },
  {
    username: "r24680",
    name: "Liam",
    email: "liam@example.com",
    password: "secure123",
    role: "Student",
  },
  {
    username: "r13579",
    name: "Ava",
    email: "ava@example.com",
    password: "avapass",
    role: "Student",
  },
  {
    username: "r11223",
    name: "Noah",
    email: "noah@example.com",
    password: "noah123",
    role: "Student",
  },
  {
    username: "r55555",
    name: "Olivia",
    email: "olivia@example.com",
    password: "pass123",
    role: "Student",
  },
  {
    username: "r11111",
    name: "Ethan",
    email: "ethan@example.com",
    password: "ethanpass",
    role: "Student",
  },
  {
    username: "r22222",
    name: "Isabella",
    email: "isabella@example.com",
    password: "isapassword",
    role: "Student",
  },
  {
    username: "r33333",
    name: "Mason",
    email: "mason@example.com",
    password: "masonpass",
    role: "Student",
  },
  {
    username: "r44444",
    name: "Sophia",
    email: "sophia2@example.com",
    password: "sophiapass",
    role: "Student",
  },
  {
    username: "r66666",
    name: "Lucas",
    email: "lucas@example.com",
    password: "lucas123",
    role: "Student",
  },
];
